// Code generated by goctl. DO NOT EDIT.
// Source: bookstore.proto

package server

import (
	"context"

	"go-zero-bookstore/app/bookstore/cmd/rpc/internal/logic"
	"go-zero-bookstore/app/bookstore/cmd/rpc/internal/svc"
	"go-zero-bookstore/app/bookstore/cmd/rpc/pb"
)

type BookstoreServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedBookstoreServer
}

func NewBookstoreServer(svcCtx *svc.ServiceContext) *BookstoreServer {
	return &BookstoreServer{
		svcCtx: svcCtx,
	}
}

// 添加book
func (s *BookstoreServer) CreateBook(ctx context.Context, in *pb.CreateBookReq) (*pb.CreateBookResp, error) {
	l := logic.NewCreateBookLogic(ctx, s.svcCtx)
	return l.CreateBook(in)
}

// 更新book
func (s *BookstoreServer) UpdateBook(ctx context.Context, in *pb.UpdateBookReq) (*pb.UpdateBookResp, error) {
	l := logic.NewUpdateBookLogic(ctx, s.svcCtx)
	return l.UpdateBook(in)
}

// 删除book
func (s *BookstoreServer) DeleteBook(ctx context.Context, in *pb.DeleteBookReq) (*pb.DeleteBookResp, error) {
	l := logic.NewDeleteBookLogic(ctx, s.svcCtx)
	return l.DeleteBook(in)
}

// 获取book
func (s *BookstoreServer) GetBook(ctx context.Context, in *pb.GetBookReq) (*pb.GetBookResp, error) {
	l := logic.NewGetBookLogic(ctx, s.svcCtx)
	return l.GetBook(in)
}

// 获取book list
func (s *BookstoreServer) GetBookList(ctx context.Context, in *pb.GetBookListReq) (*pb.GetBookListResp, error) {
	l := logic.NewGetBookListLogic(ctx, s.svcCtx)
	return l.GetBookList(in)
}
