// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Username string `json:"username"`
	Sex      int64  `json:"sex"`
	Avator   string `json:"avatar"`
	Remark   string `json:"remark"`
}

type RegisterReq struct {
	Mobile    string `form:"mobile"`
	Username  string `form:"username"`
	Password  string `form:"password"`
	Password2 string `form:"password2"`
}

type RegisterResp struct {
	Token string `json:"token"`
}

type LoginReq struct {
	Mobile   string `form:"mobile"`
	Password string `form:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type UserInfoResp struct {
	UserInfo User `json:"user_info"`
}

type UpdateUserReq struct {
	Id       int64  `form:"id"`
	Mobile   string `form:"mobile"`
	Username string `form:"username"`
	Sex      int64  `form:"sex"`
	Avatar   string `form:"avatar"`
	Remark   string `form:"remark"`
}
