// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	bookstoreCenter "go-zero-bookstore/app/bookstore/cmd/api/internal/handler/bookstoreCenter"
	"go-zero-bookstore/app/bookstore/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/bookstore-center/book",
				Handler: bookstoreCenter.CreateBookHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/bookstore-center/:id/book",
				Handler: bookstoreCenter.UpdateBookHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/bookstore-center/:id/book",
				Handler: bookstoreCenter.DeleteBookHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bookstore-center/:id/book",
				Handler: bookstoreCenter.GetBookHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bookstore-center/book-list",
				Handler: bookstoreCenter.GetBookListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/bookstore/v1"),
	)
}
