// Code generated by goctl. DO NOT EDIT.
package types

type CreateBookReq struct {
	Name  string `json:"name"`
	Price int64  `json:"price"`
	Desc  string `json:"desc"`
}

type CreateBookResp struct {
	ID int64 `json:"id"`
}

type UpdateBookReq struct {
	ID    int64  `path:"id"`
	Name  string `json:"name"`
	Price int64  `json:"price"`
	Desc  string `json:"desc"`
}

type UpdateBookResp struct {
	ID int64 `json:"id"`
}

type Book struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

type GetBookReq struct {
	ID int64 `path:"id"`
}

type GetBookResp struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

type GetBookListReq struct {
	Name     *string `form:"name,optional"`
	Price    *int64  `form:"price,optional"`
	Page     *int64  `form:"page,optional"`
	PageSize *int64  `form:"page_size,optional"`
	OrderBy  *string `form:"order_by,optional"`
}

type GetBookListResp struct {
	Books []Book `json:"books"`
}

type DeleteBookReq struct {
	ID int64 `path:"id"`
}

type DeleteBookResp struct {
	ID int64 `json:"id"`
}
